# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=20)),
                ('Description', models.TextField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('Notification_status', models.BooleanField(default=False)),
                ('Notification_time', models.DateTimeField()),
                ('Location', models.TextField(max_length=100)),
                ('Location_lat', models.DecimalField(decimal_places=4, max_digits=4)),
                ('Location_long', models.DecimalField(decimal_places=4, max_digits=4)),
                ('Tagged_users', models.ManyToManyField(related_name='tags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
