# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_calendar', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='Location_lat',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='events',
            name='Location_long',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
